### ISSUE TITLE
[Feature request] Add the ability to manage the maximum parallel downloads

### ISSUE THREAD

**Issue by Ghostotakoi** [tom5079/Pupil#112]
Hello, I have tried your app and I love it so far, that´s why I will like to request to add the ability to manage the maximum parallel download of image, like the maximum images that can be downloaded at once. This could be useful for peoples like me that have pretty bad internet connections and just by open one doujin the app suck the whole bandwidth, also if the images could load in the reading order would be nice also. Sorry for request too many things. 

Thanks in advance.

**Comment by tom5079** [comment]
Sounds good!

**Comment by tom5079** [comment]
working on issue-112

**Comment by tom5079** [comment]
This feature is added on version 5.1.8-beta1. Turn "update from beta" setting on to get a beta update.
