### ISSUE TITLE
[Feature request] Add a button to download the doujin directly

### ISSUE THREAD

**Issue by Ghostotakoi** [tom5079/Pupil#113]
Add a button to download the doujin directly without the extra step of entering inside of it. Here is an example.
![1](https://user-images.githubusercontent.com/20958581/107914441-70696200-6f30-11eb-9376-aae6385f606d.jpg)

**I also changed the favorite icon here is toggled on**
![4](https://user-images.githubusercontent.com/20958581/107914527-9ee73d00-6f30-11eb-9940-d8bdc1d42394.jpg)
These are just low quality samples.

**Comment by tom5079** [comment]
you can slide left and download

![](https://github.com/tom5079/Pupil/raw/gh-pages/assets/images/main-screenshot.jpg?raw=true)

**Comment by Ghostotakoi** [comment]
> 
> 
> you can slide left and download
> 
> ![](https://github.com/tom5079/Pupil/raw/gh-pages/assets/images/main-screenshot.jpg?raw=true)

Ok but the way I say avoid extra steps, and you also don´t need to enter in the doujin itself.

**Comment by tom5079** [comment]
what do you mean? you can just slide the card left like shown on the first screenshot
that blue button is download button

**Comment by Ghostotakoi** [comment]
@tom5079 yes I know but is not intuitive, how in the world someone would know that sliding you will find that button, for the average user all thing should be at sight, I´m just saying
