### ISSUE TITLE
[Feature request] Add a easy access tag Icon

### ISSUE THREAD

**Issue by Ghostotakoi** [tom5079/Pupil#114]
Add a easy access tag Icon, here is an example
![2](https://user-images.githubusercontent.com/20958581/107914795-2f258200-6f31-11eb-82d0-daf0223cabc2.jpg)

**Comment by tom5079** [comment]
what tag do you mean? favorite tags? recently searched tags?
what screen are you expecting to pop up when you hit that button? a dialog or a new screen?

wasn't favorite tags on search bar sufficient?

**Comment by tom5079** [comment]
how did you even create that screen? impressive stuff.

**Comment by Ghostotakoi** [comment]
@tom5079 I did the screen in Photoshop, and I expect to show maybe a new screen with different doujin tags for easy search like, this example maybe.
![3](https://user-images.githubusercontent.com/20958581/107990448-80ba2500-6fa2-11eb-94f9-367034a698aa.jpg)

**Comment by tom5079** [comment]
nice, but isn't the recommendations popping up on the search bar enough?

**Comment by Ghostotakoi** [comment]
@tom5079 this way is more intuitive I guess, you will only find the tags you have highlighted maybe ad a search bar for sear for tags.

**Comment by tom5079** [comment]
well I think what you're describing is exactly what the search bar suggestion is doing
