### ISSUE TITLE
Add favorite tags backup

### ISSUE THREAD

**Issue by ghost** [tom5079/Pupil#116]
back-up info does not contain artists or tags info yet

**Comment by tom5079** [comment]
working on branch Pupil-116

**Comment by AfrizalFirmansyah** [comment]
@tom5079 sorry to bother. sir can you add the date added look like in the website.
thank you so much.
![Screenshot (6)](https://user-images.githubusercontent.com/4180311/111658126-a5721880-883e-11eb-989e-8f561c10fb75.png)

**Comment by tom5079** [comment]
@AfrizalFirmansyah seems like it's unrelated to this issue. Can you open a new issue instead?
