### ISSUE TITLE
hiyobi.me에만 있는 갤러리일경우 갤러리 정보를 읽지 못함

### ISSUE THREAD

**Issue by CherryDrops** [tom5079/Pupil#117]
상세 설명:
히요비에는 있지만 히토미에 없는 갤러리를 다운로드 후 정보를 보려고 하면 히토미에 접속할 수 없다는 오류가 발생

이슈가 발생한 주소: https://hiyobi.me/reader/1670088

재현방법:
구글등에서 검색후 링크 클릭시 앱 선택 팝업 발생
pulil 선택 후 다운로드 진행
이후 다운로드에서 다운로드 받은 갤러리를 꾹 눌렀을때 뜨는 정보창에서 오류 메시지 발생

기대사항:
갤러리 정보가 확인되었으면 합니다

**Comment by tom5079** [comment]
source 브랜치에서 진행중

**Comment by tom5079** [comment]
hiyobi.me 서비스 종료
