### ISSUE TITLE
저장소 접근이 안 됩니다

### ISSUE THREAD

**Issue by Mango202** [tom5079/Pupil#121]
시스템 업데이트를 한 것도 아니고 앱 업데이트를 한 것도 아니고 SD카드가 망가진 것도 아닌데 저장소 내 내역이 인식이 안 됩니다..

그렇다고 저장소 내 데이터가 훼손되었나 하고 보니 용량상으로 인식은 가능하구요. 보안정책상의 사유로 화면캡쳐가 안 된다니 인증은 어려운데..

**Comment by Mango202** [comment]
버전은 5.1.9-hotfix5입니다.

**Comment by Mango202** [comment]
새로 다운받아보니 용량에 추가되고 새롭게 다운로드까지도 됩니다만 여전히 기존 다운로드 내역은 인식되지 않습니다.

**Comment by tom5079** [comment]
.download 파일이 있는지 확인해주시고 없으면 리빌드 하셔야 됩니다.

포맷은 다음과 같은 json파일입니다
```
{
    gallery_ID: "folder_name"
}
```

**Comment by tom5079** [comment]
캡쳐 안되는건 설정에서 보안모드 켜셔서 그렇습니다

**Comment by Mango202** [comment]
감사합니다
