### ISSUE TITLE
외장메모리, SD카드로 저장이 안됩니다.

### ISSUE THREAD

**Issue by STRAWBERRIESLOVER** [tom5079/Pupil#122]
안드 11 업뎃이후 SD카드 접근이나 앱 데이타로의 접근이 어려워졌는지, 저당위치를 바꿔도 내장메모리로 자동 저장됩니다.

**Comment by tom5079** [comment]
해당 위치가 쓰기 불가한 경우입니다. 다른 폴더로 선택해도 그러나요?

**Comment by STRAWBERRIESLOVER** [comment]
네, 그래서 직접 설정 기능으로 외메모리에 임의로 지정해줬더니 작동합니다

**Comment by tom5079** [comment]
안드로이드 11아닌가요?

**Comment by softkleenex** [comment]
현재도 마찬가지입니다
