### ISSUE TITLE
Gallery loading error

### ISSUE THREAD

**Issue by 616659** [tom5079/Pupil#135]
All galleries, upon first opening, fails to fully load in no matter how long I wait. So I have to first open a gallery, load it as much as possible then close and reopen, in order to load it completely. 

Wifi connection is stable, and it happens regardless of how many pages it has. 

![Screenshot_20220712-090437_Pupil](https://user-images.githubusercontent.com/51166196/178379517-6c25f820-9184-4178-b74a-98e246df302a.png)

**Comment by tom5079** [comment]
Um, I won't be able to have access to my computer for a week or two. I'll take a look when I have my computer ready.

**Comment by tom5079** [comment]
It seems like it is working fine right now, please reopen this issue if the problem persists.
