### ISSUE TITLE
搜索几乎是不可用的

### ISSUE THREAD

**Issue by rgezne** [tom5079/Pupil#137]
![Screenshot_2022-07-31-14-05-22-54](https://user-images.githubusercontent.com/110323615/182012582-5919dfdc-e0e6-40bb-9dcc-69ae6568e5cd.jpg)
![Screenshot_2022-07-31-14-05-53-58_5883791f2d4b63505f81aff3b89d061c](https://user-images.githubusercontent.com/110323615/182012591-a18a7d72-44a0-4ed4-8196-56508fe29415.jpg)
希望你们能做好，目前这个app没有用处

**Comment by tom5079** [comment]
![image](https://user-images.githubusercontent.com/7948651/182038826-84e6be33-221b-4d5b-970f-4d6809554b16.png)

It is normal to show "no results" for that search keyword.  
Try "study steady" instead.
