### ISSUE TITLE
태그 밴 같은거 만들어주실 수 있나요?

### ISSUE THREAD

**Issue by Tagbanplz** [tom5079/Pupil#138]
퍼리랑 장미물이 너무 보기 싫습니다... 걔네들 표지도 보기 싫어요 태그 밴이나 특정 태그 제외같은 기능 어떻게 안 될까요?

**Comment by tom5079** [comment]
설정 > 기본검색어에서 `-태그` 추가하세요 `-female:furry`같이

**Comment by Tagbanplz** [comment]
그건 그 태그만 보기 아닌가요? 그렇게 했더니 그 태그만 뜨던데요?

**Comment by Tagbanplz** [comment]
오 굿

**Comment by contigo** [comment]
오 - 는 뻬는건가 보내
