### ISSUE TITLE
[Feature Request] maintain zoom level in reader

### ISSUE THREAD

**Issue by 616659** [tom5079/Pupil#140]
Some galleries don't have good image ratios to read without zooming on phone (like cg) so I have to zoom to read them. Problem is when I swipe to next page it comes unzoomed, so I have to manually zoom every single page in order to read. Doing so with one hand is hard. 

So would it be possible to fix the zoom percentage for every page, so that I don't have to keep zooming myself. Thanks for your efforts

**Comment by tom5079** [comment]
The image is loaded as you scroll to save memory so it is very hard to implement the functionality you mentioned.
Why don't you try to view it in landscape mode? Check it out if it helps.

**Comment by 616659** [comment]
Yeah, but sometimes even that doesn't cut it. Maybe I should put my face closer to screen lol, thanks anyway.
