### ISSUE TITLE
[Feature Request] Hitomi.la DL enhancement

### ISSUE THREAD

**Issue by Ero-gamer** [tom5079/Pupil#150]
Feature request to add option to choose between native encoded image format: avif and jxl over webp, jpeg and png for downloads.

When I save images from hitomi.la directly while on browser, I get them as .avif image format which is better compressed compared to .webp. But when I download archive or images from Hentoid app, I always get .webp images, and there is no way to download .avif or .jxl image formats.

Possible solution: make saving individual images from Hitomi.la automated.

**Comment by tom5079** [comment]
For jpeg and png, hitomi got rid of those formats in favor of avif and webp so it does not exist on the hitomi server.

**Comment by Ero-gamer** [comment]
I know that, what I want is avif format. When I save image file on Hitomi website using Brave browser, I get .avif image format. But when I download images from Pupil app, I get images on .webp format only, no option to choose .avif format.

**Comment by tom5079** [comment]
I don't know if it is a good choice to let users download the image and not being able to display in app. If I had to add the option to download avif/jxl I think I also have to add support for displaying avif/jxl which is planned for now but not actively in development at this point.

**Comment by Ero-gamer** [comment]
> I don't know if it is a good choice to let users download the image and not being able to display in app. If I had to add the option to download avif/jxl I think I also have to add support for displaying avif/jxl which is planned for now but not actively in development at this point.

I see, thank you for your fast reply and looking forward to future update when avif/jxl format is added for download/view.

PS: consider [Coil](https://github.com/coil-kt/coil) as in-app image decoder because it is fast, lightweight, regulary updated, support avif and many other format, has the best image resampling/subsampling quality filter and it is already used by many apps including [EhViewer](https://github.com/FooIbar/EhViewer)
