### ISSUE TITLE
Crashes as soon as selecting 'Custom Location' 

### ISSUE THREAD

**Issue by loopsbrother2903** [tom5079/Pupil#156]
Version 5.3.14 on android 14. Downloading on default location doesn't work either

**Comment by tom5079** [comment]
Can you send me your user id at the bottom of the app settings page?

**Comment by loopsbrother2903** [comment]
> Can you send me your user id at the bottom of the app settings page?

fbadd4c8-8944-416e-9070-e45f4551a8e2

**Comment by tom5079** [comment]
Check if you disabled your Files app. See https://stackoverflow.com/questions/67455823/no-activity-found-to-handle-intent-open-document-tree-on-some-samsung-android-de

**Comment by tom5079** [comment]
Maybe I should alert user if Files app is disabled instead of crashing

**Comment by loopsbrother2903** [comment]
> Can you send me your user id at the bottom of the app settings page?

Sup, fixed! Pixels come w 2 default file managers, I uninstalled one earlier (one that doesn't show up on launcher) using canta. Reinstalled it and now it works fine like on my other devices.
