### ISSUE TITLE
I think the app doesn't working rn

### ISSUE THREAD

**Issue by MirhasVida** [tom5079/Pupil#157]
If you get into the main screen, no result error keep pops out.

**Comment by tom5079** [comment]
Can you try again with default search query cleared? Also please send me your user id at the bottom of the settings page.

**Comment by MirhasVida** [comment]
It's working now, however, I've cleared my cache, reinstalled, and even checked that the original cite is working, but the app doesn't work

**Comment by MirhasVida** [comment]
Yup it's not working again

bd977c2b-d9a0-48c7-b146-5d25a6c86140

**Comment by tom5079** [comment]
Can you tried clearing default search query?

**Comment by MirhasVida** [comment]
Solved

I've reinstalled my 1.1.1.1
Maybe there are some problems or crashes between Pupil and 1.1.1.1

**Comment by MirhasVida** [comment]
It's re-solved after I've reset my 1.1.1.1 data

I think there's some problem between them

**Comment by MirhasVida** [comment]
Could you please delete this issue and issue #158?

**Comment by tom5079** [comment]
It's closed so don't worry about it

**Comment by MirhasVida** [comment]
Actually, I can't find out how to hide this contribution on my profile. So if you don't mind could you please delete this issue please?
