### ISSUE TITLE
The bug with the backup.

### ISSUE THREAD

**Issue by deceit606** [tom5079/Pupil#43]
Use the restore old data to empty app.
Close app ,next time open the app ,the favorite is empty.
Have to restore and add the star again,the app really save the data.

**Comment by tom5079** [comment]
Hmm, cannot reproduce the bug btw,
restored after deleting app data and it worked 🤔

**Comment by deceit606** [comment]
if use the new data to restore for update the old favorite.
restore this can see new data in this time.
but if i do not add star again , next open the app not see the new data.
ex:
old data is d1(have 2 datas;in the old favorite );new data is d2(have 3 datas;maybe from another phone).
i use the d2 to restore to favorite.
this is i can see the new data.and the have star.
but i next time open the app,the favorite only d1 .
i have to find the new data to  close star and add star again at the restore this time.
then,next i can really to see the d2 in the favorite.
btw,restore the new data always on last favorite.
if use the page jump can not see new data,have to 1 page and 1 page ,then be able to see new data.

**Comment by tom5079** [comment]
Closed due to inactivity
