### ISSUE TITLE
about the horizontal and search

### ISSUE THREAD

**Issue by deceit606** [tom5079/Pupil#57]
when use the horizontal phone , want to see the search history ,but not have the hide keyboard.
Maybe can make the hide keyboard function.thank.

the search maybe can set the search button,the setting move to the side bar.
because every time want to search ,always needs the use keyboard's enter have some 
inconvenient.

**Comment by tom5079** [comment]
I see the point, but I doubt there's a way to resolve this problem because it's default android feature.
I'll try to fix it tho 👍

**Comment by deceit606** [comment]
https://stackoverflow.com/questions/41790357/close-hide-the-android-soft-keyboard-with-kotlin

https://inneka.com/programming/android/close-hide-the-android-soft-keyboard-with-kotlin/

maybe the can give some help
