### ISSUE TITLE
add proxy function needed

### ISSUE THREAD

**Issue by lukemin** [tom5079/Pupil#65]
I can access hitomi via proxy cause the site was blcoked by GFW. please add proxy function，thanks ahead

**Comment by tom5079** [comment]
Sounds nice, working on branch issue-65

**Comment by tom5079** [comment]
Finished implementing, but I need to test this.
Can you test this build?

**Comment by lukemin** [comment]
I updated to 4.6 beta3，but when I opened the app, update popup shows to up
to 4.5,I think it is a bug

**Comment by tom5079** [comment]
Nope, You should enable 'Update from beta channel'
Popup shows up because without that setting, the app gets update information from release channel

**Comment by lukemin** [comment]
got it, but how can I config the proxy?

**Comment by tom5079** [comment]
Uhh, I didn't updated it yet, I just asked whether you can test it
Update will be available in several hours :D

**Comment by lukemin** [comment]
ok,no problem

**Comment by tom5079** [comment]
https://github.com/tom5079/Pupil/raw/issue-65/app/release/app-release.apk
Not sure if it works... There's no way to test in here ¯\_(ツ)_/¯

**Comment by tom5079** [comment]
Let me know if it works or not or I can't add this feature to next releases

**Comment by lukemin** [comment]
socks5 proxy function works for me.

**Comment by tom5079** [comment]
Proxy support added on version 4.6!
